import PDFDocument from 'pdfkit';
import Invoice from '../models/Invoice.js';

/**
 * Generate a unique invoice number
 */
const generateInvoiceNumber = () => {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const random = Math.random().toString(36).substring(2, 8).toUpperCase();
  return `INV-${year}${month}-${random}`;
};

/**
 * Generate an invoice record after successful payment
 */
export const generateInvoice = async (payment, subscription) => {
  const invoice = await Invoice.create({
    paymentId: payment._id,
    subscriptionId: subscription._id,
    tenantId: payment.tenantId,
    tenantSlug: payment.tenantSlug,
    invoiceNumber: generateInvoiceNumber(),
    companyName: subscription.companyName,
    planName: subscription.planName,
    billingCycle: subscription.billingCycle,
    subtotal: payment.amount,
    gstPercent: payment.gstPercent,
    gstAmount: payment.gstAmount,
    total: payment.totalAmount,
    currency: payment.currency,
    billingPeriodStart: payment.billingPeriodStart,
    billingPeriodEnd: payment.billingPeriodEnd,
    status: 'Paid',
    issuedAt: new Date(),
    paidAt: payment.paidAt,
  });

  return invoice;
};

/**
 * Get invoices for a tenant
 */
export const getInvoicesByTenantId = async (tenantId) => {
  return Invoice.find({ tenantId }).sort({ createdAt: -1 });
};

/**
 * Generate PDF buffer for an invoice
 */
export const generateInvoicePdf = async (invoiceId) => {
  const invoice = await Invoice.findById(invoiceId);
  if (!invoice) throw { status: 404, message: 'Invoice not found' };

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(buffers);
        resolve({ buffer: pdfBuffer, invoice });
      });

      // Header
      doc.fontSize(24).text('EEMS', { align: 'left' });
      doc.fontSize(10).fillColor('#666').text('Enterprise Expense Management System');
      doc.moveDown(0.5);
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke('#ddd');
      doc.moveDown();

      // Invoice title
      doc.fontSize(20).fillColor('#333').text('INVOICE', { align: 'right' });
      doc.fontSize(10).fillColor('#666').text(`Invoice #: ${invoice.invoiceNumber}`, { align: 'right' });
      doc.text(`Date: ${new Date(invoice.issuedAt).toLocaleDateString('en-IN')}`, { align: 'right' });
      doc.text(`Status: ${invoice.status}`, { align: 'right' });
      doc.moveDown(2);

      // Bill To
      doc.fontSize(12).fillColor('#333').text('Bill To:');
      doc.fontSize(10).fillColor('#666').text(invoice.companyName);
      doc.text(`Tenant ID: ${invoice.tenantId}`);
      doc.moveDown(2);

      // Table header
      const tableTop = doc.y;
      doc.fontSize(10).fillColor('#333');
      doc.text('Description', 50, tableTop, { width: 250 });
      doc.text('Period', 300, tableTop, { width: 120 });
      doc.text('Amount', 450, tableTop, { width: 100, align: 'right' });
      doc.moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).stroke('#ddd');

      // Table row
      const rowTop = tableTop + 25;
      doc.fillColor('#444');
      doc.text(`${invoice.planName} Plan - ${invoice.billingCycle}`, 50, rowTop, { width: 250 });
      const periodStart = new Date(invoice.billingPeriodStart).toLocaleDateString('en-IN');
      const periodEnd = new Date(invoice.billingPeriodEnd).toLocaleDateString('en-IN');
      doc.text(`${periodStart} - ${periodEnd}`, 300, rowTop, { width: 120 });
      doc.text(`₹${invoice.subtotal.toFixed(2)}`, 450, rowTop, { width: 100, align: 'right' });

      doc.moveDown(3);
      doc.moveTo(350, doc.y).lineTo(550, doc.y).stroke('#ddd');
      doc.moveDown(0.5);

      // Totals
      const totalsX = 350;
      doc.text('Subtotal:', totalsX, doc.y, { width: 100 });
      doc.text(`₹${invoice.subtotal.toFixed(2)}`, 450, doc.y - 12, { width: 100, align: 'right' });
      doc.moveDown(0.5);
      doc.text(`GST (${invoice.gstPercent}%):`, totalsX, doc.y, { width: 100 });
      doc.text(`₹${invoice.gstAmount.toFixed(2)}`, 450, doc.y - 12, { width: 100, align: 'right' });
      doc.moveDown(0.5);
      doc.moveTo(350, doc.y).lineTo(550, doc.y).stroke('#333');
      doc.moveDown(0.5);
      doc.fontSize(12).fillColor('#333').text('Total:', totalsX, doc.y, { width: 100 });
      doc.text(`₹${invoice.total.toFixed(2)}`, 450, doc.y - 14, { width: 100, align: 'right' });

      // Footer
      doc.moveDown(4);
      doc.fontSize(9).fillColor('#999').text('This is a computer-generated invoice and does not require a signature.', { align: 'center' });
      doc.text('Generated by EEMS Billing System', { align: 'center' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};
