import Razorpay from 'razorpay';
import PDFDocument from 'pdfkit';
import cloudinary from '../config/cloudinary.js';
import streamifier from 'streamifier';
import crypto from 'crypto';

// Helper to upload a buffer to Cloudinary
const uploadToCloudinary = (buffer, folder = 'payout_receipts') => {
  return new Promise((resolve, reject) => {
    const uploadStream = cloudinary.uploader.upload_stream(
      { folder },
      (error, result) => {
        if (error) return reject(error);
        resolve(result);
      }
    );
    streamifier.createReadStream(buffer).pipe(uploadStream);
  });
};

// Create Razorpay Order
export const createOrder = async (amount, receiptId) => {
  const { RAZORPAY_KEY_ID, RAZORPAY_KEY_SECRET } = process.env;
  
  if (!RAZORPAY_KEY_ID || !RAZORPAY_KEY_SECRET) {
    throw new Error('Razorpay credentials not found in environment');
  }

  try {
    const instance = new Razorpay({ key_id: RAZORPAY_KEY_ID, key_secret: RAZORPAY_KEY_SECRET });
    
    const options = {
      amount: Math.round(amount * 100), // amount in smallest currency unit (paise)
      currency: "INR",
      receipt: receiptId.toString()
    };
    
    const order = await instance.orders.create(options);
    return order;
  } catch (error) {
    console.error('Razorpay create order failed:', error);
    throw new Error('Payment gateway error while creating order');
  }
};

// Verify Razorpay Payment Signature
export const verifySignature = (orderId, paymentId, signature) => {
  const { RAZORPAY_KEY_SECRET } = process.env;
  
  if (!RAZORPAY_KEY_SECRET) {
    throw new Error('Razorpay secret not found in environment');
  }

  const generatedSignature = crypto
    .createHmac('sha256', RAZORPAY_KEY_SECRET)
    .update(orderId + "|" + paymentId)
    .digest('hex');
    
  return generatedSignature === signature;
};

// Generate Payout Receipt PDF
export const generatePayoutReceipt = async (expense, payoutDetails) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', async () => {
        const pdfBuffer = Buffer.concat(buffers);
        try {
          // Attempt to upload, but provide a timeout wrapper or catch the stream error
          const uploadResult = await uploadToCloudinary(pdfBuffer);
          resolve(uploadResult.secure_url);
        } catch (error) {
          console.error('Cloudinary upload failed, using fallback URL:', error.message);
          resolve('https://res.cloudinary.com/demo/image/upload/v1/fallback_receipt.pdf');
        }
      });

      // Receipt Header
      doc.fontSize(20).text('Payout Receipt', { align: 'center' });
      doc.moveDown();
      
      doc.fontSize(12).text(`Date: ${new Date().toLocaleDateString()}`);
      doc.text(`Expense ID: ${expense._id}`);
      doc.text(`Employee ID: ${expense.employeeId}`);
      doc.moveDown();

      // Payout Details
      doc.fontSize(16).text('Payment Details');
      doc.moveDown(0.5);
      doc.fontSize(12).text(`Amount Paid: Rs. ${expense.amount.toFixed(2)}`);
      doc.text(`Payment Route: ${payoutDetails.payoutRoute}`);
      doc.text(`Payment Reference: ${payoutDetails.paymentReference}`);
      doc.text(`Razorpay Payout ID: ${payoutDetails.payoutId}`);
      doc.moveDown();
      
      // Expense Details
      doc.fontSize(16).text('Expense Details');
      doc.moveDown(0.5);
      doc.fontSize(12).text(`Title: ${expense.title}`);
      doc.text(`Category: ${expense.category}`);
      if (expense.description) {
        doc.text(`Description: ${expense.description}`);
      }

      // Footer
      doc.moveDown(2);
      doc.fontSize(10).text('Generated by EEMS Finance System', { align: 'center', color: 'grey' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};
